<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <ProjectStyle>SDK</ProjectStyle>
    <ChaosAnalyzers_CleanCode_Analyzer_TF>netstandard2.0</ChaosAnalyzers_CleanCode_Analyzer_TF>
    <ChaosUtil_Primitives_Analyzer_TF>netstandard2.0</ChaosUtil_Primitives_Analyzer_TF>
    <ChaosGenerators_Analyzer_TF>netstandard2.0</ChaosGenerators_Analyzer_TF>
    <ChaosGenerators_Types_Analyzer_TF>netstandard2.0</ChaosGenerators_Types_Analyzer_TF>
  </PropertyGroup>

  <Import Project="ChaosFramework.Math.props" />

  <!-- Included Files -->
  <ItemGroup>
    <Compile Include="source/**/*.cs" />
    <None Include="License/**/*.txt" />
    <None Include="OpenTK.dll.config" />
  </ItemGroup>

  <!-- References -->
  <Import Project="submodules/ChaosPresets.References/Analyzers.Dll/ChaosUtil.Primitives.targets" />
  <Import Project="submodules/ChaosPresets.References/Analyzers.Dll/ChaosGenerators.Types.targets" />
  <Import Project="submodules/ChaosPresets.References/Analyzers.Dll/ChaosGenerators.targets" />
  <ItemGroup>
    <PackageReference Include="OpenTK" Version="3.0.1" />
    <PackageReference Include="System.Drawing.Common" Version="8.0.6" />
  </ItemGroup>

</Project>