<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <ProjectStyle>SDK</ProjectStyle>
  </PropertyGroup>

  <Import Project="ChaosFramework.Math.props" />

  <!-- Included Files -->
  <ItemGroup>
    <Compile Include="source/**/*.cs" />
    <None Include="License/**/*.txt" />
    <None Include="OpenTK.dll.config" />
  </ItemGroup>

  <!-- References -->
  <ItemGroup>
    <PackageReference Include="OpenTK" Version="3.0.1" />
  </ItemGroup>

</Project>