<?xml version="1.0" encoding="utf-8"?>
<Project DefaultTargets="Build" ToolsVersion="14.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Import
    Project="$(MSBuildExtensionsPath)/$(MSBuildToolsVersion)/Microsoft.Common.props"
    Condition="Exists('$(MSBuildExtensionsPath)/$(MSBuildToolsVersion)/Microsoft.Common.props')"
    />

  <PropertyGroup>
    <ProjectStyle>VS</ProjectStyle>
    <ChaosAnalyzers_CleanCode_Analyzer_TF>net4.5</ChaosAnalyzers_CleanCode_Analyzer_TF>
    <ChaosUtil_Primitives_Analyzer_TF>net4.5</ChaosUtil_Primitives_Analyzer_TF>
    <ChaosGenerators_Analyzer_TF>net4.5</ChaosGenerators_Analyzer_TF>
    <ChaosGenerators_Types_Analyzer_TF>net4.5</ChaosGenerators_Types_Analyzer_TF>
    <ChaosGenerators_Types_Ref_TF>net4.5</ChaosGenerators_Types_Ref_TF>
  </PropertyGroup>

  <Import Project="submodules/ChaosPresets.Targets/Frameworks/net4.5.2.targets" />
  <Import Project="submodules/ChaosPresets.Targets/Paths/Output/bin.targets" />
  <Import Project="ChaosFramework.Math.props" />

  <!-- Included Files -->
  <ItemGroup>
    <Compile Include="source\**\*.cs" />
    <Compile Include="generated\**\*.cs" />
    <Compile Include="Properties\AssemblyInfo.cs" />
    <None Include="License\**\*.txt" />
    <None Include="OpenTK.dll.config" />
    <None Include="packages.config" />
  </ItemGroup>

  <!-- References -->
  <Import Project="submodules/ChaosPresets.References/References/ChaosGenerators.Types.targets" />
  <Import Project="submodules/ChaosPresets.References/Analyzers.Dll/ChaosGenerators.Types.targets" />
  <ItemGroup>
    <Reference Include="System" />
    <Reference Include="System.Drawing" />

    <Reference Include="OpenTK, Version=3.0.1.0, Culture=neutral, PublicKeyToken=bad199fe84eb3df4, processorArchitecture=MSIL">
      <HintPath>$(SolutionDir)\packages\OpenTK.3.0.1\lib\net20\OpenTK.dll</HintPath>
      <Private>True</Private>
    </Reference>
  </ItemGroup>

  <!-- Cleanup Tasks -->
  <Import Project="submodules/ChaosPresets.References/BuildTasks/ChaosBuild.ProjectAnalyzer.targets" />
  <Import Project="submodules/ChaosPresets.References/BuildTasks/ChaosBuild.CodeFormatter.Tasks.ChangedProjectFiles.targets" />

  <!-- Default Targets for Building CSharp Projects -->
  <Import Project="$(MSBuildToolsPath)/Microsoft.CSharp.targets" />
</Project>